INSERT INTO role_permissions (role_name, permission_key) VALUES
('ADMIN', 'MANAGE_USERS'), ('ADMIN', 'CONFIG_PERMISSIONS'), ('ADMIN', 'MONITOR_SYSTEM'), ('ADMIN', 'BACKUP_DATA'),
('STORE_MANAGER', 'MANAGE_INVENTORY'), ('STORE_MANAGER', 'GENERATE_REPORTS'), ('STORE_MANAGER', 'MANAGE_STORES'), ('STORE_MANAGER', 'MANAGE_REQUESTS'),
('SALES_EMPLOYEE', 'REGISTER_SALES'), ('SALES_EMPLOYEE', 'PROCESS_RETURNS'), ('SALES_EMPLOYEE', 'VIEW_INVENTORY'), ('SALES_EMPLOYEE', 'GENERATE_INVOICE'),
('LOGISTICS', 'MANAGE_SHIPMENTS'), ('LOGISTICS', 'OPTIMIZE_ROUTES'), ('LOGISTICS', 'UPDATE_ORDER_STATUS'), ('LOGISTICS', 'MANAGE_SUPPLIERS'),
('CUSTOMER', 'CREATE_ACCOUNT'), ('CUSTOMER', 'BROWSE_PRODUCTS'), ('CUSTOMER', 'PLACE_ORDER'), ('CUSTOMER', 'WRITE_REVIEW');